### ISSUE TITLE
Change date format for data selection component to ISO 8601

### ISSUE THREAD

**Issue by arendd** [IPK-BIT/miappe-wizard#16]
MIAPPE wants to have ISO 8601 for date YYYY-MM-DD 
→ is shown correct in the ISA-JSON but not in the date field there we have DD-MM-YYYY (german format)
→ this is because currently we use <input type=”date” /> which is formatted by the browser according to the language settings of the OS

**Comment by patrick-koenig** [comment]
Discarded!
